[package]
name = "server"
version = "0.1.0"
authors = ["liteng <yujinjianixin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
actix-web = "3"
anyhow = "1.0.40"
async-graphql = { version = "2.8.2", features = ["chrono", "uuid", "apollo_tracing", "log"] }
async-graphql-actix-web = "2.8.2"
config = "0.11.0"
dotenv = "0.15.0"
log = "0.4.14"
log4rs = { version = "1.0.0", features = ["toml_format"] }
serde = "1.0.125"
serde-aux = "2.2.0"
chrono = { version = "0.4.19", features = ["serde"] }
sqlx = { version = "0.4.2", features = ["runtime-actix-native-tls", "uuid", "postgres", "chrono"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
thiserror = "1.0.24"
serde_json = "1.0.64"
validator = "0.13.0"
validator_derive = "0.13.0"
jsonwebtoken = "7.2.0"
argonautica = { version = "0.2", features = ["serde"] }