[package]
name = "server"
version = "0.1.0"
authors = ["liteng <yujinjianixin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
anyhow = "1.0.40"
async-graphql = { version = "2.8.2", features = ["chrono"] }
async-graphql-actix-web = "2.8.2"
config = "0.11.0"
dotenv = "0.15.0"
log = "0.4.14"
log4rs = { version = "1.0.0", features = ["toml_format"] }
serde = "1.0.125"
serde-aux = "2.2.0"
sqlx = { version = "0.5.2", features = ["runtime-actix-rustls", "macros", "postgres", "uuid", "chrono", "migrate", "offline"] }
